### ISSUE TITLE
Watch server adapter changes

### ISSUE THREAD

**Issue by Tjark-Kuehl** [universal-vue/uvue#10]
**Describe the bug**
I'm using the new adapters feature to create an Api on the same server.
For this I'm using Koa with all its packages.
Now when I set the `watch` property in the server.config.js and change some text on my server the server restarts twice but the text is not updated on window reload.

**To Reproduce**
Go to /api in the browser and see a basic api output.
Now go to src/api/routes/index.js and change the body message.
The server should restart now but when you reload the text is still the old text

[**Repository**](https://github.com/Tjark-Kuehl/uvue-reproduction)

**Expected behavior**
Show the updated text on page reload

**Additional context**

Please indicate versions of:
```
node: 11.x
vue-cli: Newest
uvue: Newest
os: Ubuntu 18.10 / Windows 10
browser: Google Chrome 70
```

**Comment by chymz** [comment]
Fixed in `0.1.0-alpha.6`
