### ISSUE TITLE
Blank page on fresh install

### ISSUE THREAD

**Issue by John-Ciuchea** [universal-vue/uvue#18]
**Describe the bug**
Fresh vue project and uvue install does not work

**To Reproduce**
Fresh new vue project created via vue ui or cli.
The project uses: babel, router (history mode), vuex, and ESLint airbnb.
Install uvue via vue ui or vue cli.
Run npm run ssr:serve.
Nothing is showed in browser.

[**Reproduction repo/demo link**](#url-here)

**Expected behavior**
Welcome screen should display

**Additional context**

Please indicate versions of:
```
node: 11.0.0
vue-cli: 3.2.1
uvue: 0.1.0-alpha
os: macOS 10.14.3
browser: Chrome 71.0.3578.98
```

**Comment by chymz** [comment]
As workarround please rename or remove `public/index.html` file.

It will be fixed in next version

**Comment by John-Ciuchea** [comment]
Removing `public/index.html` did fix my issue. Thanks for your fast reply!
