### ISSUE TITLE
[feature] Adding new strategy fetching data on server side for vue 2.6

### ISSUE THREAD

**Issue by academici** [universal-vue/uvue#20]
In the new update vue 2.6, vue-server-renderer has changed the data loading strategy for SSR.
Previously, we were advised to call asyncData() methods on components received via router.getMatchedComponents(), [more detail here](https://github.com/vuejs/vue/commit/42fdf3f8378e5dc379808a4fa67b39c4a74ae191).
The new version has a special method for components - serverPrefetch(). vue-server-renderer will call it on each component and wait for the solution of the returned promises:
```js
<template>
  <div v-if="item">
    {{ item.name }}
  </div>
</template>

<script>
export default {
  // Called on the server
  async serverPrefetch() {
    await this.fetchItem();
  },

  computed: {
    item() {
      return this.$store.state.item;
    },
  },

  // Called on the client
  mounted() {
    if (!this.item) {
      this.fetchItem();
    }
  },

  methods: {
    async fetchItem() {
      await this.$store.dispatch('fetchItem');
    },
  },
};
</script>
```

**Comment by chymz** [comment]
Actually 2.6 is still in beta, so... waiting ;)

**Comment by academici** [comment]
@chymz, i know, but they have not written about it yet

**Comment by chymz** [comment]
See #25
