### ISSUE TITLE
can u add req/res to onHttpRequest's context?

### ISSUE THREAD

**Issue by xurwxj** [universal-vue/uvue#26]
can u add req/res to onHttpRequest's context?
It's for the convenience of getting header/cookie from req where process.server is true.

**Comment by chymz** [comment]
Which adapter do you use ?

**Comment by xurwxj** [comment]
express

**Comment by chymz** [comment]
Sorry I cannot reproduce `req` and `res` are present in UVue context:

```js
async onHttpRequest({ commit }, { req, res }) {
  console.log(req, res);
}
```

PS: there is a template to fill issue, please respect it !

**Comment by xurwxj** [comment]
@chymz tks a lot for your reply.  It looks like I'm in the wrong way.
At the same time, tks for your reminder. Next time, i'll submit in accordance with the rules.
