### ISSUE TITLE
build --modern cause vue-simple-uploader null object

### ISSUE THREAD

**Issue by xurwxj** [universal-vue/uvue#28]
**Describe the bug**
using [vue-simple-uploader](https://github.com/simple-uploader/vue-uploader) to upload file in app, when build without --modern, all works well, otherwise will got following error:
```
Uncaught TypeError: Cannot convert undefined or null to object
```
**To Reproduce**
Steps to reproduce the behavior.
1. get the demo repo
2. yarn install
3. yarn run ssr:build
4. yarn run ssr:start
5. choose a file to upload on ui of /
upload success without error!
6. yarn run ssr:build --modern
7. yarn run ssr:start
8. choose a file to upload on ui of /
you will get above error.
[**Reproduction repo/demo link**](https://github.com/xurwxj/uvued.git)

**Expected behavior**

**Additional context**

Please indicate versions of:
```
node: v10.15.0
vue-cli: V3.3
uvue: 0.1.0-alpha.17
os: mac 10.14.3
browser: chrome 72.0.3626.119
```

**Comment by chymz** [comment]
I think you need to fix some issues in your code:

First, install and setup Vue No SSR correctly `yarn add vue-no-ssr` and:
```js
import NoSSR from 'vue-no-ssr';
Vue.component('no-ssr', NoSSR);
```

Then fix not defined reference here: https://github.com/xurwxj/uvued/blob/master/src/views/Home.vue#L62

Actually with these fixes I did not encouter your provided error...

**Comment by xurwxj** [comment]
@chymz I've update the repo according your suggest, but still get above error on chrome's console.

**Comment by chymz** [comment]
Sorry dude, I did not reproduce your issue, maybe it's because I dont have your backend/API to test it correctly...

**Comment by xurwxj** [comment]
@chymz you can copy the demo.js to conf.js to run with my backend/api to test.
