### ISSUE TITLE
Add runInNewContext option to renderer options

### ISSUE THREAD

**Issue by academici** [universal-vue/uvue#39]
Option runInNewContext: true is useful for static sites for better performance.

**Comment by chymz** [comment]
Hey,

you can already pass this option to vue renderer via server.config.js (but it's undocumented):

```js
export default {
  renderer: {
    runInNewContext: true
  }
}
```

Anyway, can you link me where you found that this config is better for performance in this case ? Vue SSR docs the opposite:

> However, this mode comes at some considerable performance cost because 
> re-executing the bundle is expensive especially when the app gets bigger.

https://ssr.vuejs.org/api/#runinnewcontext

**Comment by chymz** [comment]
Docs updated
