### ISSUE TITLE
Type conflict

### ISSUE THREAD

**Issue by jfcieslak** [universal-vue/uvue#42]
**Describe the bug**
Subsequent property declarations must have the same type.  Property 'env' must be of type 'ProcessEnv', but here has type '{ [name: string]: string; }'.ts(2717)
globals.d.ts(848, 9): 'env' was also declared here.

```typescript
//@uvue/core/global.d.ts
declare namespace NodeJS {
  export interface Process {
  // env should be type: ProcessEnv
    env: {
      [name: string]: string;
    };
    ssr: boolean;
    spa: boolean;
    client: boolean;
    server: boolean;
    prod: boolean;
    test: boolean;
    dev: boolean;
  }
}

```

**To Reproduce**
This type error is a typings collision ts(2717) caused by the fact that env is also declared in globals.d.ts(848, 9)

[**Reproduction repo/demo link**](#url-here)

**Expected behavior**
Should not get a type error from ts

**Additional context**

Please indicate versions of:
```
node: v12.13.1
vue-cli:  4.1.1
uvue: 0.1.1
os: mac os catalina 10.15.1
browser: chrome
```

**Comment by lsotoangeldonis** [comment]
Hi hope it helps, had the same issue a work around is to put "skipLibCheck": true in your tsconfig.json under "compilerOptions".
