### ISSUE TITLE
devServer.proxy: Not working with ssr:serve

### ISSUE THREAD

**Issue by SwapnilSoni1999** [universal-vue/uvue#49]
By using `npm run ssr:serve` it is not working with the configuration provided in `vue.config.js`

![image](https://user-images.githubusercontent.com/25403317/78907238-142aeb80-7a9e-11ea-9a07-196d526350f2.png)

But when `npm run serve` is used it is working! Can anyone point me out where I'm wrong or its internal missing feature of uvue or something?

**In short:**
- `devServer.proxy` is not working with `npm run ssr:serve` from `vue.config.js`
-  when `npm run serve` is used! it is working. but problem is it is not ssr

**Additional context**

```
node: v13.12.0
vue-cli: v4.2.3
uvue: 0.1.0
os: ArchLinux
browser: Google Chrome
```

**Comment by Lord-Y** [comment]
I have the same problem and spent hours on it :pensive: . Did you figure it out @SwapnilSoni1999 ? If not maybe @chymz can give us a help :thinking: . All my axios requests don't reach my API server

**Comment by chymz** [comment]
Sorry for late response.

UVue doesn't use webpack dev server, that's why this configuration is ignored.
Instead, you can create your own [server plugin](https://universal-vue.github.io/docs/plugins/server.html#write-your-own-plugin) to use a http proxy middleware.

For example if you use default server adapter or express:

```js
const { createProxyMiddleware } = require('http-proxy-middleware');

export default {
  install(app) {
    if (process.env.NODE_ENV !== 'production') {
      const proxyOptions = {
        target: 'https://api.example.com',
        changeOrigin: true,
        ws: true,
      };

      app.use('/api', createProxyMiddleware(proxyOptions));
    }
  }
}
```

And install it like explained here: https://universal-vue.github.io/docs/plugins/#server

**Comment by SwapnilSoni1999** [comment]
> Sorry for late response.
> 
> UVue doesn't use webpack dev server, that's why this configuration is ignored.
> Instead, you can create your own [server plugin](https://universal-vue.github.io/docs/plugins/server.html#write-your-own-plugin) to use a http proxy middleware.
> 
> For example if you use default server adapter or express:
> 
> ```js
> const { createProxyMiddleware } = require('http-proxy-middleware');
> 
> export default {
>   install(app) {
>     if (process.env.NODE_ENV !== 'production') {
>       const proxyOptions = {
>         target: 'https://api.example.com',
>         changeOrigin: true,
>         ws: true,
>       };
> 
>       app.use('/api', createProxyMiddleware(proxyOptions));
>     }
>   }
> }
> ```
> 
> And install it like explained here: https://universal-vue.github.io/docs/plugins/#server

will checkout surely

**Comment by SwapnilSoni1999** [comment]
> I have the same problem and spent hours on it  . Did you figure it out @SwapnilSoni1999 ? If not maybe @chymz can give us a help  . All my axios requests don't reach my API server

same, so Im thinking to learn Nuxt and move my stuff in nuxt
