### ISSUE TITLE
Uvue Dev tools with Node version >12.

### ISSUE THREAD

**Issue by phlegx** [universal-vue/uvue#51]
**Is your feature request related to a problem? Please describe.**
Install of `@uvue/devtools` with Node version > 12 not possible.

**Describe the solution you'd like**
Using `@uvue/devtools` with Node version > 12.

**Describe alternatives you've considered**
Downgrade to Node version < 13.

**Comment by chymz** [comment]
Thanks for reporting, I'll upgrade some packages to fix this

**Comment by yabab-dev** [comment]
Try UVue `0.1.7` ;)
