### ISSUE TITLE
Deploy with PM2

### ISSUE THREAD

**Issue by vasilyman** [universal-vue/uvue#53]
**Describe the bug**
How to deploy with pm2 manager? Standart script (pm2 start npm --name 'name-app' -- ssr:start)  give error

**To Reproduce**
Steps to reproduce the behavior.

[**Reproduction repo/demo link**](#url-here)

**Expected behavior**

**Additional context**

Please indicate versions of:
```
node: v12.16.1
vue-cli: 
uvue: 
os: ubunto 20.04
browser: 
```

**Comment by chymz** [comment]
Hi @vasilyman ,

I've no issue with PM2 actually, what is your error message ? If I run `pm2 start "npm run ssr:start"` everything is working as expected.

**Comment by yabab-dev** [comment]
No answer, closing
