### ISSUE TITLE
Now V2 / Lambda deployment

### ISSUE THREAD

**Issue by dohomi** [universal-vue/uvue#6]
Hi @chymz 
I'm currently playing around with the new version of now which basically wraps application code through builder to run serverless functions. 
Is it possible to run a server of the pre-builded sources similar like the functional approach starting NuxtJS programatically?
I found this very basic example: https://github.com/zeit/now-examples/tree/master/vue-ssr
It would be great to add an example of using uvue on the now infrastructure
Cheers

**Comment by dohomi** [comment]
That would be great! Now v2 is giving be big headaches at the moment. None of my Nuxt projects where able to convert from v1 => v2 yet

**Comment by chymz** [comment]
Finally got it working!

What I've done:
1. Switched from `yarn` to `npm` (yarn seems buggy with now)
2. Moved 2 cypress `devDependencies` to `peerDependencies` to have a faster build
3. Created Now needed files
4. Made a shell script to build app and remove `devDependencies` from `node_modules`

Now my package is 22mb of files, and :tada: 

https://uvue-examples-1o0lbwihq.now.sh/

Full commit here: https://github.com/universal-vue/examples/commit/f8deae00767ac77b7b703f078d2ab377a0f2fcef

**Comment by chymz** [comment]
Added in docs: https://universal-vue.github.io/docs/guide/deploy.html#now-v2

**Comment by dohomi** [comment]
@chymz cool thanks for doing that.
I haven't much dipped into this package yet, but what I am doing with NuxtJS is following:

1. deploy the `/.nuxt/dist/client`statically under a different subdomain as static files (as CDN)
2. update `build.publicPath` inside nuxt.config.js to point to public files CDN domain of 1.)
3. deploy the server as npm project into now

That gave me very nice results for Pagespeed and Lighthouse
Not sure if thats possible with this package but I'm sure you can archive the same with the different bundler section for the public client side files after building the project. Cheers and keep up the great work
