### ISSUE TITLE
REDIRECT_ERROR in uvue plugin hook

### ISSUE THREAD

**Issue by camwhite** [universal-vue/uvue#9]
**Describe the bug**

Hitting `REDIRECT_ERROR` when calling `redirect` on the `context` in a uvue plugin's `beforeCreate` hook.

**To Reproduce**

```
export default {
  beforeCreate ({ redirect }) {
    redirect('/about')
  }
}
```

[**Reproduction demo link**](https://codesandbox.io/s/m32j90kv09)

**Expected behavior**

A redirect to the passed route.

**Additional context**

Please indicate versions of:
```
node: 10.5
vue-cli: 3.2.1
uvue: 0.1.0-alpha
os: ubuntu
browser: chrome
```

**Comment by chymz** [comment]
Fixed in `0.1.0-alpha.6`
